---
- name: Install Podman 
  yum:
    name: podman
    state: latest
    update_cache: yes
  become: true
  tags: deps

- name: Ensure Podman running
  service:
    name: podman
    state: started
    enabled: yes
  become: true
  tags: deps
