---
- name: Install Podman 
  yum:
    name:
      - podman>=3.3.0
    state: present
  become: true
  tags: deps

- name: Ensure Podman running
  service:
    name: podman
    state: started
    enabled: yes
  become: true
  tags: deps
  
#- name: install Ansible podman
#  community.general.ansible_galaxy_install:
#    type: collection
#    name: containers.podman
#  delegate_to: localhost
