---
- name: Test Variables
  include_tasks: test_vars.yaml
  tags: tests, deploy

- name: Install dependencies
  include_tasks: deps.yaml
  tags: deps

- name: Deploy pod
  include_tasks: deploy.yaml
  tags: deploy

- name: Cleanup
  include_tasks: cleanup.yaml
  tags: never, cleanup

- name: Redner Config map
  command: echo "{{lookup('template', 'configmap.j2') }}" 
  register: output  
  tags: never, configmap

- name: Print template
  debug:
    var: output.stdout_lines
  tags: never, configmap
